Renamed HEADLESS_CLIENT to DISPLAY_TYPE
OpenAstroTech/OpenAstroTracker pull request #103
Opened 2020-10-17 00:19 UTC by andre-stefanov

Renamed HEADLESS_CLIENT definition to DISPLAY_TYPE

2020-10-17 01:37 UTC, ClutchplateDude requested changes

2020-10-17 01:37 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/Configuration_adv.hpp
> +#define DISPLAY_TYPE DISPLAY_TYPE_NONE
This is not longer the case. We can attach a display to thw ESP32 now, so we shouldn't force this.

2020-10-17 01:37 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/Constants.hpp
> +#define DISPLAY_TYPE_LCD_KEYPAD     1
I think we need more comments about what this is. Like "LCD shield on top Mega" and "I2C LCD Display" or something :-)

2020-10-17 09:28 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/Constants.hpp
> +#define DISPLAY_TYPE_LCD_KEYPAD     1
Good point, i will add more descriptions

2020-10-17 09:28 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/Configuration_adv.hpp
> +#define DISPLAY_TYPE DISPLAY_TYPE_NONE
Ah good to know, I'll remove it

2020-10-18 01:18 UTC, ClutchplateDude approved these changes

2020-10-18 01:18 UTC, merged