Develop
OpenAstroTech/OpenAstroTracker pull request #114
Opened 2020-11-17 00:44 UTC by CTetford

-Make LCD pins configurable 
-bug fixes

2020-11-17 01:10 UTC, andre-stefanov requested changes

2020-11-17 01:10 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
> +#include "../Configuration_pins.hpp"
please change to `inc/Config.hpp`

2020-11-17 01:10 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/LcdMenu.cpp
> +#include "../Configuration_pins.hpp"
please change to `inc/Config.hpp`

2020-11-17 11:03 UTC, andre-stefanov requested changes

2020-11-17 11:03 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/Configuration_pins.hpp
> +        #define LCD_PIN9 9
Please name these definitions by actual pin names on the LCD shield

2020-11-17 15:12 UTC, andre-stefanov commented
Don't merge this PR yet. i will maybe have to refactor the code a bit to fit in our coding conventions and/or best practices

2020-11-17 15:39 UTC, CTetford commented on Software/Arduino code/OpenAstroTracker/Configuration_pins.hpp
> +        #define LCD_PIN9 9
The pins on the LCD shields are not labelled. The next best reference would be their intended pins on the Arduino Mega they are designed for.

2020-11-19 06:56 UTC, ClutchplateDude requested changes

2020-11-19 06:56 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/Configuration_adv.hpp
> +#define DEW_HEATER 1
This should be off by default

2020-11-19 15:47 UTC, CTetford commented on Software/Arduino code/OpenAstroTracker/Configuration_adv.hpp
> +#define DEW_HEATER 1
Agreed - this was leftover from testing.

2020-11-19 17:36 UTC, ClutchplateDude approved these changes

2020-11-26 11:40 UTC, andre-stefanov requested changes
This PR is still not building for several configurations. We need to fix them before merging.

2020-11-27 19:01 UTC, andre-stefanov approved these changes

2020-11-27 19:36 UTC, merged