Removed mainLoopTask to avoid kernal panic due to re-entrancy on TWI …
OpenAstroTech/OpenAstroTracker pull request #126
Opened 2020-11-29 17:54 UTC by philharrisathome

…from multiple loop(). loop() now runs on Core1 (Arduino default) and steppers run on Core 0. This fix allows I2C displays to work on ESP32. It will also allow Gyro to work on ESP32 but need to fix some minor compilation issues first. Removed separate finishSetup() - setup() just continues on.
Some minor updates to logging as well.

2020-12-05 08:47 UTC, ClutchplateDude approved these changes

2020-12-06 01:45 UTC, ClutchplateDude requested changes
This is a great PR, Phil, just some small requests. Totally appreciate your contribution here!

2020-12-06 01:45 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
> -  mount.readConfiguration();
Why was the readConfiguration() call removed?

2020-12-06 01:45 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/EPROMStore.cpp
> +#if USE_DUMMY_EEPROM == 1
Curious what you needed this for?

2020-12-06 01:45 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Gyro.cpp
> +    Wire.write(0x75);   // WHO_AM_I
Can you use some defined constants here for all the magic hex numbers to indicate that they mean, please?

2020-12-06 01:45 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Gyro.cpp
> +        return 99.9;     // Gyro is not available
May want to return 0 instead, or does 99.9 fit on the LCD display?

2020-12-06 01:46 UTC, ClutchplateDude commented
And let's get this one merged before you add any more features not related to kernel panics :-)

2020-12-12 22:36 UTC, philharrisathome commented on Software/Arduino code/OpenAstroTracker/src/Gyro.cpp
> +        return 99.9;     // Gyro is not available
Starting with the easy ones: the display formatting truncates this to nearest degree so it fits. See formula at end of function that returns arbitrary float also. Though of returning 0, but it is possible 0 would be seen in normal operation - I wanted to indicate clear fault.

2020-12-12 22:38 UTC, philharrisathome commented on Software/Arduino code/OpenAstroTracker/src/Gyro.cpp
> +    Wire.write(0x75);   // WHO_AM_I
Agreed. Will do this.

2020-12-12 22:44 UTC, philharrisathome commented on Software/Arduino code/OpenAstroTracker/src/EPROMStore.cpp
> +#if USE_DUMMY_EEPROM == 1
I implemented an in-memory version to verify that the bugs I found in NVM buffer overrun and swapping of DEC upper/lower limits were the only ones. It is redundant now TBF. Ideally I'd like to refactor all of scaling of EPROM data into dedicated get/set functions in EPROMStore: having these spread through the main body makes maintenance & review hard.

2020-12-12 22:51 UTC, philharrisathome commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
> -  mount.readConfiguration();
There were two calls to readConfiguration() in this function. I deleted this one (the 1st) and kept the 2nd (line 259) as tracing showed that the configuration data was not accessed before the 2nd instance.

2020-12-12 22:53 UTC, philharrisathome commented on Software/Arduino code/OpenAstroTracker/src/Gyro.cpp
> +    Wire.write(0x75);   // WHO_AM_I
If you are happy to accept this then I will submit a subsequent PR with the named constants.

2020-12-13 01:04 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Gyro.cpp
> +    Wire.write(0x75);   // WHO_AM_I
We are :-)

2020-12-13 01:05 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/EPROMStore.cpp
> +#if USE_DUMMY_EEPROM == 1
Oh this is so true!

2020-12-13 01:08 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Gyro.cpp
> +    Wire.write(0x75);   // WHO_AM_I
Note that you will have to move over to the new repo (OpenAstroTracker-Firmware) if you do this in a later PR, since we are closing the current repo for Firmware after your PR.

2020-12-13 01:09 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Gyro.cpp
> +    Wire.write(0x75);   // WHO_AM_I
Mh if you promise it :) then we would be even happier with that. We are currently migrating the firmware code to a new repository and current 2 open PRs here are blocking us from removing the code from the old repository. You can then simply create a new PR to the new repository (i will copy your changes to the new repo as fast as possible).

2020-12-13 01:13 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Gyro.cpp
> +        return 99.9;     // Gyro is not available
mh sounds reasonable. then let us make a define `#define GYRO_VALUE_NOT_AVAILABLE 99.0` or something similar, return it here and then on the display side we could compare to this value and maybe even return a special message. Also this way the return here would be readable.

2020-12-13 01:24 UTC, andre-stefanov requested changes

2020-12-13 01:24 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Gyro.hpp
> +struct angle_t { float pitchAngle = 0; float rollAngle = 0; };
mh ... you are defining "default" pitch and roll values with 0 in multiple spots of the code. what if the gyro does not respond properly and you return these values. Instead of being able to handle this issue correctly, the tracker will just use 0 and think that it is leveled.

2020-12-13 11:05 UTC, philharrisathome commented on Software/Arduino code/OpenAstroTracker/src/Gyro.hpp
> +struct angle_t { float pitchAngle = 0; float rollAngle = 0; };
Yes, so no worse than not having the gyro installed/configured, but still potentially misleading. We are missing a general way to inform the user of subsystem faults, whether it be gyro, gps, wifi, ... . I guess a better approach here is to modify the menu code to check for availability of gyro and display message during levelling functions. I can look into this.

2020-12-13 11:07 UTC, philharrisathome commented on Software/Arduino code/OpenAstroTracker/src/Gyro.cpp
> +    Wire.write(0x75);   // WHO_AM_I
Ok, probably easier. I'll stash what I have, move to current OpenAstroTracker-Firmware, and place new PRs.

2020-12-14 11:46 UTC, andre-stefanov commented
Closing since @philharrisathome has kindly migrated this PR to the new repository: https://github.com/OpenAstroTech/OpenAstroTracker-Firmware/pull/8

2020-12-14 11:46 UTC, closed without merging