Added support for UART based communication with connection checking
OpenAstroTech/OpenAstroTracker pull request #129
Opened 2020-12-03 13:44 UTC by pmneo

Using UART communication to wait for the driver to be ready before applying settings,

2020-12-03 17:07 UTC, ClutchplateDude requested changes

2020-12-03 17:07 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _driverRA->microsteps(2);
Why this change?

2020-12-03 17:07 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  sprintf(scratchBuffer, "Connecting to DEC");
These status strings are all too long. You only have 15 characters available on the top row and 16 on the bottom.

2020-12-03 18:49 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _driverRA->microsteps(2);
FULLSTEP is not defined, so i have changed it to 1 and that did not worked. But this change should not be commited. My Fault. Sorry for that.

2020-12-03 18:51 UTC, andre-stefanov requested changes

2020-12-03 18:51 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/Configuration.hpp
> +#define TMC_USE_UART      0
we have the DRIVER_TYPE_TMC2209_UART already ... it looks like this definition is redundant to it

2020-12-03 18:51 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  sprintf(scratchBuffer, "Connecting to RA");
does the connection take long? if not this menu text will be shown to short and appear just as a flicker

2020-12-03 18:51 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _driverRA->microsteps(2);
wait ... the autohome code is not functional yet. did you activate it in the configs?

2020-12-03 18:52 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  sprintf(scratchBuffer, "Connecting to DEC");
Did not recognized that. Good spot....

2020-12-03 18:52 UTC, andre-stefanov commented
Also please create changes from develop to develop. master is meant for releases

2020-12-03 18:54 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/Configuration.hpp
> +#define TMC_USE_UART      0
Yes, but the "DRIVER_TYPE_TMC2209_UART" uses PDN per default without any need to wire RX.

2020-12-03 18:55 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  sprintf(scratchBuffer, "Connecting to RA");
It depends on how fast the driver came up. Sometimes the "Connecting to RA" is never shown. But this ensures, that the Microsteps are set.

2020-12-03 18:55 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _driverRA->microsteps(2);
i have tested it via the local conf.

2020-12-03 18:56 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _driverRA->microsteps(2);
FULLSTEP is definitely defined.
Also, I notice that this is a request to master branch. We do not accept PR's straight into master. Please only submit PRs to the develop branch.

2020-12-03 19:01 UTC, andre-stefanov requested changes

2020-12-03 19:01 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  sprintf(scratchBuffer, "Connecting to RA");
But then we could just display a message if it failed (persistently) and maybe even halt the arduino instead of sometimes displaying the progress message.

2020-12-03 19:01 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _driverRA->pdn_disable(true); //enable UART
isn't `mstep_reg_select ` also needed in this case? and maybe even more ...

2020-12-03 19:11 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  sprintf(scratchBuffer, "Connecting to DEC");
Did you not test this?

2020-12-03 19:48 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  sprintf(scratchBuffer, "Connecting to DEC");
Usualy DEC is not shown, because of the order (RA, then DEC) ...

2020-12-03 19:49 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  sprintf(scratchBuffer, "Connecting to RA");
In this case we may skip the connection message and only show the connection failed messages.

2020-12-03 19:52 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _driverRA->pdn_disable(true); //enable UART
I will take a deeper look into it. The not applied microsteps where my cause of using uart. Since this changes the steppings are well applied.

2020-12-04 06:13 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _driverRA->microsteps(2);
@ClutchplateDude Can't find any Symbol named "FULLSTEP" neither in master nor in develop. There is only a FULLSTEP_MODE defined with 4.

Ich will close this Pull Request and create a new improved one in develop.

2020-12-04 06:14 UTC, pmneo commented
Because of wrong branch and some improvements todo.

2020-12-04 06:14 UTC, closed without merging