Indi Driver: Autocalculate HA from Date / Time and Longitude
OpenAstroTech/OpenAstroTracker pull request #132
Opened 2020-12-04 08:50 UTC by pmneo

This will use Sideral to calculate HA when using the OAT with indilib.

This also provides some more data to the driver (Time Format 24h, Device Time and Date, and Dummy Site names) to avoid errors during Driver startup.

This also includes my fix for the wrong Latitude interpretation and extends the Info Menu by two more Pages (Driver Date and Driver UTC Time)

2020-12-05 08:45 UTC, ClutchplateDude requested changes

2020-12-05 08:45 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Longitude.cpp
> +  result.totalSeconds = 0 - dt.getTotalSeconds();
Let's rather fix the ParseFromMeade() function.

2020-12-05 08:45 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +      return "(24)#";
The Meade spec I have doesn't have parentheses here.

2020-12-05 08:45 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +      char achBuffer[20];
Let's move this buffer outside the switch, I believe that will save memory. Not sure whether the compiler reserves space for all 4 or just one as it is used.

2020-12-05 08:45 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +    case 'M': {
Any specific reason you implemented these? Do you have more than one OAT? Does some app make use of this?

2020-12-05 08:45 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +const int MeadeCommandProcessor::year() const {
All these function s should be added to the Mount class. The command processor doesn't really have a time and location associated with it, that's more of a Mount property.

2020-12-05 08:45 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +       sprintf(scratchBuffer, "Error Status: %d", testConnection);
Is the error code always between -9 and 99? Do you have a list of possible errors?

2020-12-05 08:45 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +       delay(2000);
This seems long, one second should be fine,no?

2020-12-05 08:45 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +    for(int i=0; i<5; i++) {
All this code can be refactored into a function into which you pass the driver and some text. It's essentially identical between RA and DEC.

2020-12-05 08:45 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
> +    #endif
Should there if an #else with an #error here in case someone forgot to define something? Or is that the normal case?

2020-12-05 08:45 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/c78_menuINFO.hpp
> +        sprintf(scratchBuffer, "DrY: %04d-%02d-%02d", mcp->year(), mcp->month(), mcp->day() );
What does the DrY stand for here?

2020-12-08 10:32 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Longitude.cpp
> +  result.totalSeconds = 0 - dt.getTotalSeconds();
ParseFromMeade is used several times, this behaviour affects only longitute...

2020-12-08 10:34 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +      return "(24)#";
My Specs are from here: https://www.astro.louisville.edu/software/xmtel/archive/xmtel-indi-6.0/xmtel-6.0l/support/lx200/CommandSet.html#LX-200CmdSetAutostarGETcommand

The Indi-Driver can deal with both variants

2020-12-08 10:35 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +    case 'M': {
The Indi driver is fetching this data

2020-12-08 10:38 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +       sprintf(scratchBuffer, "Error Status: %d", testConnection);
Not really, there are only 3 codes handled:

`
uint8_t TMCStepper::test_connection() {
  uint32_t drv_status = DRV_STATUS();
  switch (drv_status) {
      case 0xFFFFFFFF: return 1;
      case 0: return 2;
      default: return 0;
  }
}
`

2020-12-08 10:38 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +       delay(2000);
OK

2020-12-08 10:39 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/c78_menuINFO.hpp
> +        sprintf(scratchBuffer, "DrY: %04d-%02d-%02d", mcp->year(), mcp->month(), mcp->day() );
Should be Date or somthing else than DrY ...

2020-12-08 10:42 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
> +    #endif
You're right, i will add an else with error message

2020-12-08 13:30 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +const int MeadeCommandProcessor::year() const {
I will refactor this

2020-12-08 13:30 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +      char achBuffer[20];
I will refactor this

2020-12-08 13:39 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +    for(int i=0; i<5; i++) {
I will refactor this

2020-12-08 16:17 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +      return "(24)#";
There's quite a few specs floating about. That one is from 2002. We've been using one from 2007 and it doesn't have parentheses. Since the Indi driver understands both, can we remove them?

2020-12-08 17:00 UTC, ClutchplateDude requested changes

2020-12-09 08:13 UTC, ClutchplateDude requested changes

2020-12-09 08:13 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  lstDeg -= ( ( POLARIS_RA_MINUTE/60.0f + POLARIS_RA_HOUR + POLARIS_RA_SECOND ) * 15.0f );
This is incorrect. I think you want:
lstDeg -= ( ( POLARIS_RA_SECOND/3600.0 + POLARIS_RA_MINUTE/60.0f + POLARIS_RA_HOUR) * 15.0f );

2020-12-09 08:13 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +    this->_mount->setLocalUtcOffset( inCmd[1] == '+' ? offset : -offset );
ping

2020-12-09 08:13 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +    return "1Updating Planetary Data#                              #"; //
Wow, I totally missed that there is another blank string behind the first one. This change will break OATControl and maybe the ASCOM driver. We will need to check that.

2020-12-09 08:13 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +       sprintf(scratchBuffer, "Error Status: %d", testConnection);
ping

2020-12-09 08:13 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  #if NORTHERN_HEMISPHERE == 1
ping

2020-12-09 11:44 UTC, andre-stefanov requested changes

2020-12-09 11:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +       delay(1000);
why is this long delay needed?

2020-12-09 11:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Sidereal.cpp
> +DayTime Sidereal::calculateByDriver( double longitude, int year, int month, int day, DayTime *timeUTC ) {
I suppose it should be called `calculateByDateAndTime`

2020-12-09 11:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +      char sign = offset < 0 ? '-' : '+';
sprintf `+` prefix can be used to add the sign in positive and negative values instead of doing it manually

2020-12-09 11:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +    int testConnection;
rename to `connectionStatus`

2020-12-09 11:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +       delay(1000);
Also if we have driver connection issues, we should probably stop here completely because whole tracker wont work anyway.

2020-12-09 11:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  this->_localTimeSetMillis = -1;
why isn't it simply part of DayTime?

2020-12-09 11:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  this->_localUtcOffset = 0;
I think the offset can also be part of DayTime

2020-12-09 11:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  DayTime timeUTC = this->_localTime;
considering this logic, we should rename the `_localTime` member to something proper e.g. `_localStartTime`

2020-12-09 11:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  return this->_localDate;
_localData could have changed over time (especially since we are using the tracker at night). You have add here the time since bootup as well.

2020-12-09 11:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +DayTime Mount::calculateHa() {
I think these calculations should be done inside of `Sidereal`

2020-12-09 11:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.hpp
> +  DayTime calculateHa();
can be private

2020-12-09 11:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.hpp
> +  void autoCalcHa();
can be private

2020-12-09 11:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
> +  #if RA_DRIVER_TMC2209_UART_MODE == TMC2209_MODE_UART
this looks like it should be done in the pin configuration

2020-12-09 11:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
> +      #error RA: Can not use UART with Software Serial
why is it not possible to use software serial?

2020-12-11 01:28 UTC, CTetford commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
> +      #error RA: Can not use UART with Software Serial
I think this should be debugged rather than abandoned - the MKS board will need softwareserial for UART Rx.

Also pins should never be hardcoded.

2020-12-13 00:55 UTC, andre-stefanov commented
Please give us a feedback to the comments. Otherwise we will close it in context of the repository migration.

2020-12-13 08:26 UTC, pmneo reviewed
I will implement the changes next week

2020-12-13 08:26 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +      char sign = offset < 0 ? '-' : '+';
Okay, didn't know that

2020-12-13 08:26 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +    int seconds = inCmd.substring( 7, 9 ).toInt();
I will check this

2020-12-13 08:26 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  this->_localUtcOffset = 0;
But then every DayTime instance will have ist, while only one case needs that information?

2020-12-13 08:26 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +DayTime Mount::calculateHa() {
I will move it

2020-12-13 08:26 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.hpp
> +  void autoCalcHa();
Ok

2020-12-13 08:26 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Sidereal.cpp
> +DayTime Sidereal::calculateByDriver( double longitude, int year, int month, int day, DayTime *timeUTC ) {
Ok

2020-12-13 21:13 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  this->_localUtcOffset = 0;
mh ... good point. unfortunatelly since the DateTime is kind of misused for DEC, an offset would not make any sense there

2020-12-13 21:33 UTC, CTetford commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
> +      #error RA: Can not use UART with Software Serial
Could you explain what errors you were having or, what you attempted?

2020-12-14 05:55 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
> +      #error RA: Can not use UART with Software Serial
With SoftwareSerial the connection test is not working, it seems that is not able to read any data from the stepper.

I haven't tried any other pins, but i can't imagine that this makes a different, while Hardware Serial works fine.

2020-12-14 11:43 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Longitude.cpp
> +  result.totalSeconds = 0 - dt.getTotalSeconds();
will it work with ASCOM then?

2020-12-14 12:01 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Longitude.cpp
> +  result.totalSeconds = 0 - dt.getTotalSeconds();
Don't have the capabilities to test ASCOM

2020-12-14 12:03 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +      sprintf(achBuffer, "%02d:%02d:%02d#", time.getHours(), time.getMinutes(), time.getSeconds());
I decided to use formatString, same thing is used for longitude and latitude in MeadeCommandProcessor

2020-12-14 12:55 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +    case 'M': {
I'm using LX200 Classic driver, at it requests :GL#, :GG# at driver start:

`
[2020-12-14T09:28:29.071 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:GR#> "
[2020-12-14T09:28:29.071 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] RES <15:45:04> "
[2020-12-14T09:28:29.071 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] Coordinate format is high precision. "
[2020-12-14T09:28:29.072 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] <ACK> "
[2020-12-14T09:28:29.072 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <0X6> "
[2020-12-14T09:28:29.072 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] RES <1> "
[2020-12-14T09:28:29.072 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] <getTimeFormat> "
[2020-12-14T09:28:29.072 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:Gc#> "
[2020-12-14T09:28:29.072 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] RES <24> "
[2020-12-14T09:28:29.073 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] <getSiteName> "
[2020-12-14T09:28:29.073 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:GM#> "
[2020-12-14T09:28:29.073 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] RES <OAT1> "
[2020-12-14T09:28:29.073 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[DEBUG] Site Name <OAT1> "
[2020-12-14T09:28:29.073 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] <getTrackFreq> "
[2020-12-14T09:28:29.073 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:GT#> "
[2020-12-14T09:28:29.073 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] RES <60.0#> "
[2020-12-14T09:28:29.074 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] VAL [60] "
[2020-12-14T09:28:29.074 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] <getSiteLatitude> "
[2020-12-14T09:28:29.074 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:Gt#> "
[2020-12-14T09:28:29.074 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] RES <+47*56> "
[2020-12-14T09:28:29.074 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] VAL [47,56] "
[2020-12-14T09:28:29.074 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] <getSiteLongitude> "
[2020-12-14T09:28:29.074 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:Gg#> "
[2020-12-14T09:28:29.075 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] RES <+10*44> "
[2020-12-14T09:28:29.075 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] VAL [10,44] "
[2020-12-14T09:28:29.075 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[DEBUG] Mount Controller Latitude: 47.9333 Longitude: 349.267 "
[2020-12-14T09:28:29.075 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[DEBUG] Configuration successfully saved for GEOGRAPHIC_COORD. "
[2020-12-14T09:28:29.075 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:GG#> "
[2020-12-14T09:28:29.076 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] RES <-01> "
[2020-12-14T09:28:29.076 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] VAL [-1] "
[2020-12-14T09:28:29.076 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:GL#> "
[2020-12-14T09:28:33.256 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] <getCalendarDate> "
[2020-12-14T09:28:33.256 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:GC#> "
[2020-12-14T09:28:33.284 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] RES <12/14/20> "
[2020-12-14T09:28:33.284 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[DEBUG] Mount controller UTC Time: 2020-12-13T23:00:00 "
[2020-12-14T09:28:33.284 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[DEBUG] Mount controller UTC Offset: 1.00 "
[2020-12-14T09:28:33.319 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[DEBUG] InitPark Axis1 0.00 Axis2 47.93 "
[2020-12-14T09:28:33.320 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[DEBUG] Setting Default Park Axis1 to 0.00 "
[2020-12-14T09:28:33.320 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[DEBUG] Setting Default Park Axis2 to 47.93 "
[2020-12-14T09:28:33.320 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:GR#> "
[2020-12-14T09:28:33.320 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] RES <15:45:04> "
[2020-12-14T09:28:33.320 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] VAL [15.7511] "
[2020-12-14T09:28:33.321 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:GD#> "
[2020-12-14T09:28:33.321 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] RES <+90*00'00> "
[2020-12-14T09:28:33.322 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] VAL [90] "
[2020-12-14T09:28:33.322 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[DEBUG] Toggle Debug Level -- Scope Verbose "
[2020-12-14T09:28:33.324 UTC INFO ][           org.kde.kstars.indi] - LX200 Classic :  "[INFO] Loading device configuration... "
[2020-12-14T09:28:33.366 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[DEBUG] Toggle Debug Level -- Scope Verbose "
[2020-12-14T09:28:33.367 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[DEBUG] Toggle Logging Level -- Messages "
[2020-12-14T09:28:33.368 UTC INFO ][           org.kde.kstars.indi] - LX200 Classic :  "[INFO] Dome Policy set to: Dome ignored. Mount can park or unpark regardless of dome parking state. "
[2020-12-14T09:28:33.369 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[DEBUG] Active Snoop, driver: Dome Simulator, property: DOME_PARK "
[2020-12-14T09:28:33.369 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] <setSiteLongitude> "
[2020-12-14T09:28:33.369 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:Sg010:44#> "
[2020-12-14T09:28:33.370 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:Sg010:44#> successful. "
[2020-12-14T09:28:33.370 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] <setSiteLatitude> "
[2020-12-14T09:28:33.370 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:St+47:56:00#> "
[2020-12-14T09:28:33.371 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:St+47:56:00#> successful. "
[2020-12-14T09:28:33.372 UTC INFO ][           org.kde.kstars.indi] - LX200 Classic :  "[INFO] Site location updated to Lat  47:56:00 - Long  349:16:00 "
[2020-12-14T09:28:33.373 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[DEBUG] Configuration successfully saved for GEOGRAPHIC_COORD. "
[2020-12-14T09:28:33.374 UTC INFO ][           org.kde.kstars.indi] - LX200 Classic :  "[INFO] Observer location updated: Longitude (-10.7333) Latitude (47.9333) "
[2020-12-14T09:28:33.375 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] <setSlewMode> "
[2020-12-14T09:28:33.375 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] CMD <:RM#> "
[2020-12-14T09:28:33.376 UTC INFO ][           org.kde.kstars.indi] - LX200 Classic :  "[INFO] Pulse guiding is enabled. "
[2020-12-14T09:28:33.377 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] <setMaxSlewRate> "
[2020-12-14T09:28:33.377 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "Error setting maximum slew rate. "
[2020-12-14T09:28:33.377 UTC DEBG ][           org.kde.kstars.indi] - LX200 Classic : "[SCOPE] <setMinElevationLimit> "
[2020-12-14T09:2 [...]

2020-12-15 06:26 UTC, ClutchplateDude requested changes

2020-12-15 06:26 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/Configuration.hpp
> +#define RA_DRIVER_TMC2209_CONNECTION_TEST      DISABLE
These two should read DISABLED, not DISABLE (since that is undefined)

2020-12-15 06:26 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Longitude.cpp
> +  result.totalSeconds = 0 - dt.getTotalSeconds();
This needs to be tested with ASCOM before we can merge it. Not saying you need to do it, but one of us does.

2020-12-15 06:31 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/Configuration.hpp
> +#define RA_DRIVER_TMC2209_CONNECTION_TEST      DISABLE
Have changed it, my fault sorry.

2020-12-15 08:21 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/Configuration.hpp
> +#define RA_DRIVER_TMC2209_CONNECTION_TEST      DISABLED
@ClutchplateDude these should not be part of Configuration.hpp since it's by far not one of the main config value (most users wont even know what it is). Probably Configuration_adv.hpp is better to use here

2020-12-15 08:27 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/Configuration.hpp
> +#define RA_DRIVER_TMC2209_CONNECTION_TEST      DISABLED
Oh, yeah, I didn't even notice what file that was in...

2020-12-15 09:46 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +      return "60.0#"; //default MEADE Tracking Frequency
i tried to find out what this value actally is and it seems that this value is a specific value of LX200 hardware. Apparently it is the frequency of the quartz crystal used in this specific mount. It can be changed to have other tracking speeds/rates in order to track other objects as stars (e.g. sun or moon). So for now we can keep it at 60.1. Hz since LX200 uses this frequency for star tracking. At some point we could think about extending this with some logic (especially if we want to support other tracking speeds some day).

2020-12-15 09:48 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +       delay(1000);
one option could be to display an appropriate error message on the screen and enter an endless loop.

2020-12-15 09:52 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  #if NORTHERN_HEMISPHERE == 1
I think what @ClutchplateDude meant was that limits to the right are the same as to the left while the code uses 7 and 5 hours limits (which we don't understand). 

I don't really get the point of slew to the east when tracking west. The slew of RA cant be chosen freely since it influences DEC axis movements. You can point to a target only if RA and DEC are set to a specific value.

Also the RA ring limits should not be chosen by hours, but by hardware (RA ring) dimensions.

2020-12-15 09:55 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
> +    #endif
This looks like it should be part the configuration and not b_setup

2020-12-15 13:50 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  #if NORTHERN_HEMISPHERE == 1
I will try to explain it better, as far as i have tested, the v4 wheel can move from +7h to -7h from parking position. 

The goal of this change is, to move eagerly to east, because tracking will move to west. 
Because of the 7h limit a target can be reached with relative RA position of >5h (of parking pos) it will be accessible on both sides. So this will flip the axis an RA-hour earlier.

2020-12-15 13:51 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/Configuration.hpp
> +#define RA_DRIVER_TMC2209_CONNECTION_TEST      DISABLED
Can move it to adv conf

2020-12-15 13:52 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
> +    #endif
Hmm, than the SoftwareSerial will be declared / instantiated in configuration.hpp ... don't know if this is the right place

2020-12-15 13:58 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
> +    #endif
the software serial should be initialized outside of the config by using the defines from the config

2020-12-15 13:59 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
> +    #endif
in this code few things got mixed: defines for the actual configuration of the pins or ports and also their usage in stream instances

2020-12-15 14:34 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  #if NORTHERN_HEMISPHERE == 1
Are you maybe talking about a meridian flip?

2020-12-15 14:39 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  #if NORTHERN_HEMISPHERE == 1
ok after some more reading of surrounding code i now get the problem.

2020-12-15 15:32 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  #if NORTHERN_HEMISPHERE == 1
Ok sorry for all the confusion, i think i got it now:
- the whole thing is about the meridian flip
- until now OAT flipped around at least 6 hours after the target crossed the meridian
- you change reduces this to 5 hours (earlier flip is not possible because the ring does not provide more freedom on the other side)

2020-12-15 15:32 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  #if NORTHERN_HEMISPHERE == 1
The main question of mine at this point is ... what advantage do we get by doing so?

2020-12-15 19:22 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  #if NORTHERN_HEMISPHERE == 1
To have Always the Maximum Flip free Tracking time. I will make this conifgureable via adv config.

2020-12-15 20:11 UTC, CTetford commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  #if NORTHERN_HEMISPHERE == 1
But it will just flip again once it reaches the 5 hour mark....you still have the same duration available for tracking (12 hrs).

It's just taking an hour of tracking from before the flip and moving it to after the flip - there is no net increase in tracking time.

2020-12-15 21:51 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  #if NORTHERN_HEMISPHERE == 1
Does is automicaly flip while Tracking? Isn't that code only used for slew?

2020-12-16 12:11 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  #if NORTHERN_HEMISPHERE == 1
Well while controlling the mount manually, this will happen only if we slew to a target (goto). While controlled over Meade this code will be called on a SYNC command. So you are correct here :) pure tracking won't be using the meridian flip logic and simply go on until ... well ... RA ring end was reached. Based on this fact, you really are getting here 1 hour more of tracking if there was a slew to this target previously (which is the common case).

2020-12-16 12:14 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  #if NORTHERN_HEMISPHERE == 1
Do we also take into account the DEC limitation? Dec ring cant be rotated to the -90° position (iirc) for example because there is a gap. It would be a disaster if we make a meridian flip based only on the RA limitations and make an "unexpected quick disassembly" because of the DEC limitation.

2020-12-16 12:26 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  #if NORTHERN_HEMISPHERE == 1
I have pushed a bit of documentation and formatting in order to make this topic more understandable

2020-12-22 07:26 UTC, ClutchplateDude commented
@pmneo  We will likely not accept this review as you keep adding things to it. You will need to make separate PRs for each feature, since this is not an acceptable way of merging new code into the repo. We need small chunks with one new feature in it, not a mega PR that keeps changing even though we've been reviewing it. You should address all the comments on it and make the requested changes instead adding new features.

2020-12-22 07:31 UTC, ClutchplateDude requested changes

2020-12-22 07:31 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +      switch( inCmd[1] ) {
No, the LX200 spec clearly says these are lowercase. The 'g' is indeed not uppercase, that is a bug, but the directions are lower case only.

2020-12-22 07:47 UTC, pmneo commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +      switch( inCmd[1] ) {
So then your code was completely wrong, because the original code only uses upper case.

2020-12-22 07:48 UTC, pmneo commented
@ClutchplateDude How to prevent GitHub to automatically add my commits to this pull request?

2020-12-22 07:55 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/MeadeCommandProcessor.cpp
> +      switch( inCmd[1] ) {
Yes, you are indeed correct.

2020-12-22 07:57 UTC, ClutchplateDude commented
> @ClutchplateDude How to prevent GitHub to automatically add my commits to this pull request?

You use branches. From the command line, you do `git checkout -b my-feature`, if you're using a GUI client, there's probably a Create Branch command.... then you commit and push the features of that branch. To switch between branches you just uses teh same command without the `-b`.

2020-12-22 11:04 UTC, andre-stefanov commented
> @pmneo We will likely not accept this review as you keep adding things to it. You will need to make separate PRs for each feature, since this is not an acceptable way of merging new code into the repo. We need small chunks with one new feature in it, not a mega PR that keeps changing even though we've been reviewing it for weeks. You should address all the comments on it and make the requested changes instead of adding new features.

Unfortunately i have to agree on that. Your ideas are good, but it's really hard to keep overview of the changes. Please create separate branches based on the develop of the new repo. Each "feature branch" should contain only one feature/change. Then create a PR for each of them agains the develop. Otherwise it is not possible to get all the use cases and possible side effects tested properly.

2020-12-22 11:06 UTC, andre-stefanov commented
Please create separate PRs as described in the comment above by following [these rules](https://github.com/OpenAstroTech/OpenAstroTracker-Firmware#contribution).

2020-12-22 11:06 UTC, closed without merging

2020-12-23 06:36 UTC, pmneo commented
@andre-stefanov where is the code from develop branch gone?

2020-12-23 07:48 UTC, andre-stefanov commented
> @andre-stefanov where is the code from develop branch gone?

As stated in the comments above, the code is in the new repo.

2020-12-23 08:50 UTC, pmneo commented
Oo ... how to create the pull requests from my old fork?

2020-12-23 08:55 UTC, andre-stefanov commented
> Oo ... how to create the pull requests from my old fork?

You will have to make a new fork and apply the changes there since the history there does not contain same hashes and can't be reused this way. The easiest way would be to fork, create feature branches and just copy your changes there. Then a pr as usual.