fixed trackign speed calculation
OpenAstroTech/OpenAstroTracker pull request #136
Opened 2020-12-06 20:48 UTC by andre-stefanov

2020-12-06 21:16 UTC, ClutchplateDude approved these changes
LCD should probably be adjusted to allow precise adjustments to step/degree. Or should we remove that altogether?

2020-12-06 23:13 UTC, ClutchplateDude requested changes

2020-12-06 23:13 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _trackingSpeed = _trackingSpeedCalibration * RA_STEPS_PER_DEGREE * TRACKING_MICROSTEPPING * 360.0 / (23.0*60.0*60.0 + 56.0*60.0 + 4.0905);
So we're ignoring the EPROM values altogether?

2020-12-06 23:13 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _trackingSpeed = _trackingSpeedCalibration * RA_STEPS_PER_DEGREE * 360.0 / (23.0*60.0*60.0 + 56.0*60.0 + 4.0905);
Can we put the day length in a variable once?

2020-12-06 23:33 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _trackingSpeed = _trackingSpeedCalibration * RA_STEPS_PER_DEGREE * TRACKING_MICROSTEPPING * 360.0 / (23.0*60.0*60.0 + 56.0*60.0 + 4.0905);
absolutelly, it would be `86164.0905` seconds (to keep it short since the name already tells what it is)

2020-12-06 23:35 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _trackingSpeed = _trackingSpeedCalibration * RA_STEPS_PER_DEGREE * 360.0 / (23.0*60.0*60.0 + 56.0*60.0 + 4.0905);
absolutelly, it would be 86164.0905 seconds (to keep it short since the name already tells what it is)

2020-12-06 23:44 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _trackingSpeed = _trackingSpeedCalibration * RA_STEPS_PER_DEGREE * 360.0 / (23.0*60.0*60.0 + 56.0*60.0 + 4.0905);
done

2020-12-06 23:45 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _trackingSpeed = _trackingSpeedCalibration * RA_STEPS_PER_DEGREE * TRACKING_MICROSTEPPING * 360.0 / (23.0*60.0*60.0 + 56.0*60.0 + 4.0905);
no we dont, we still use _trackingSpeedCalibration here at the moment

2020-12-06 23:45 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _trackingSpeed = _trackingSpeedCalibration * RA_STEPS_PER_DEGREE * TRACKING_MICROSTEPPING * 360.0 / (23.0*60.0*60.0 + 56.0*60.0 + 4.0905);
the bigger question is ... do we really still need the calibration? how big can be the printing error?

2020-12-07 04:38 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/Mount.cpp
> +  _trackingSpeed = _trackingSpeedCalibration * RA_STEPS_PER_DEGREE * TRACKING_MICROSTEPPING * 360.0 / (23.0*60.0*60.0 + 56.0*60.0 + 4.0905);
I meant the RA step value in EPROM..

2020-12-08 20:46 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/inc/Globals.hpp
> +extern int DECStepsPerDegree;
alright, got explained that it is needed by LCD (and only LCD)

2020-12-09 00:14 UTC, merged