ESP32 bluetooth serial
OpenAstroTech/OpenAstroTracker pull request #99
Opened 2020-10-15 21:07 UTC by mholeys

Added support for the ESP32 to be used via bluetooth
Enabled using HEADLESS_BLUETOOTH 
Uses the same MeadeCommandProcessor as Serial and seems to work with both connected

Tested on:
- ESP32 (Adafruit board)
- Stellarium on Android
- OTA control connects and controls via bluetooth serial port

I have not field tested this at all, only basic movement

2020-10-16 06:32 UTC, ClutchplateDude requested changes
Thank you very much for your submission. I had a few comments. Feel free to address or ignore them, but we would obviously appreciate it more if you addressed them :-).

2020-10-16 06:32 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/f_serial.hpp
> +                if (inCmd.charAt(1) == 0x06) {
What is this case covering? Why might there be a 0x06 at the second position? What is first? If I send I#, this code will crash since inCmd is only 1 char long.

2020-10-16 06:32 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/f_serial.hpp
> +                if (inCmd == "Ka") {
It would be good if you could add comments as to what these commands are and what they accomplish....

2020-10-16 06:32 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/src/f_serial.hpp
> +                    LOGV2(DEBUG_SERIAL, F("Didnt reply %s"), retVal);
Change this to just LOGV1(DEBUG_SERIAL, F("No reply"));

2020-10-16 06:32 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/Configuration_adv.hpp
> +// #define HEADLESS_BLUETOOTH 1
Let's change this to USE_BLUETOOTH instead of HEADLESS_BLUETOOTH. It's not really required to be headless, we could add a BT module to the Mega with shield....

2020-10-16 13:11 UTC, mholeys commented
I will look into those comments, and clean some bits up that I had missed

2020-10-16 13:19 UTC, andre-stefanov commented
What i we have two connection (usb serial and bluetooth at the same time?) both would call `mount.loop()` ... could this be an issue?

2020-10-16 13:19 UTC, andre-stefanov requested changes

2020-10-16 13:19 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/b_setup.hpp
>    //BT.begin(9600);
This line can be removed? i know that it was here before this PR but if we already touch BT, we could clean up at least a bit.

2020-10-16 13:19 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/f_serial.hpp
> +bool bt_connected = false;
we should export all the bluetooth stuff into a separate .hpp / .cpp files ... it does not really have any relationship to the serial logic.

2020-10-16 13:21 UTC, mholeys commented on Software/Arduino code/OpenAstroTracker/src/f_serial.hpp
> +bool bt_connected = false;
Should I move this over to the other unused bluetooth file then?

2020-10-16 13:23 UTC, mholeys commented on Software/Arduino code/OpenAstroTracker/src/f_serial.hpp
> +                if (inCmd.charAt(1) == 0x06) {
Looking through what Stellaris sends when it trys to connect via bluetooth. It attempts to connect via NexStar, then fails, then when trying LX200 it sends # followed by ACK, which is the reason for this check. I think the response should be Alignment Query. Do you think there is a better way to catch this case?

2020-10-16 13:23 UTC, andre-stefanov commented on Software/Arduino code/OpenAstroTracker/src/f_serial.hpp
> +bool bt_connected = false;
Huh, there is another unused bluetooth file? (don't have my IDE at the moment). If there is one and it is really not used at all, then we should concider to merge their logic or even remote the old one if it is completelly obsolete in context of this PR

2020-10-16 13:34 UTC, mholeys commented on Software/Arduino code/OpenAstroTracker/src/f_serial.hpp
> +bool bt_connected = false;
I was talking in reference to g_bluetooth.hpp, it has a single funtion (BTin) which is all commented out. Is this being used? I used this as the base for this PR.

2020-10-16 13:46 UTC, mholeys commented on Software/Arduino code/OpenAstroTracker/Configuration_adv.hpp
> +// #define HEADLESS_BLUETOOTH 1
Would BLUETOOTH_ENABLED be better as to be similar to WIFI_ENABLED

2020-10-16 13:58 UTC, mholeys commented on Software/Arduino code/OpenAstroTracker/src/f_serial.hpp
> +                if (inCmd.charAt(1) == 0x06) {
Check for an empty command just a '#' has tidied this up slightly

2020-10-16 15:18 UTC, mholeys commented
I have done some of the requested changes, but I am not sure on the best way for the following things:
- mount.loop() - I do not understand the code enough to change this?
- There is a check in the bluetooth loop that replies to a 0x06 (ACK) which is what stellarium looks for to test it is LX200 compatible, but I was not sure if this should be within the MeadeCommandProcessor? I haven't done this as it is different in the serialLoop it just replies 1. (Info from https://www.meade.com/support/LX200CommandSet.pdf)

2020-10-16 15:28 UTC, ClutchplateDude commented on Software/Arduino code/OpenAstroTracker/Configuration_adv.hpp
> +// #define HEADLESS_BLUETOOTH 1
Yes, even better.

2020-10-16 15:29 UTC, ClutchplateDude commented
> What i we have two connection (usb serial and bluetooth at the same time?) both would call `mount.loop()` ... could this be an issue?
> 
> Not in context of this PR: In general we should not call mount.loop() from hardware components. it should be the other way around.

Not really.
Any component that does something that might take a long time should call mount.loop().

2020-10-16 15:30 UTC, ClutchplateDude commented
> * There is a check in the bluetooth loop that replies to a 0x06 (ACK) which is what stellarium looks for to test it is LX200 compatible, but I was not sure if this should be within the MeadeCommandProcessor? 
Well, technically we could, but the serial loop also tests it outside the MCP. This is fine.

2020-10-16 15:36 UTC, ClutchplateDude approved these changes

2020-10-16 15:36 UTC, mholeys commented
Ok, is there anything else that you want? Do you want me to do any specific tests to check things are working fully? I have not had a chance to use the mount at all with the weather

2020-10-16 16:20 UTC, ClutchplateDude commented
> Ok, is there anything else that you want? 
No, this is great! We'll make any changes needed as we work on the code in general.

2020-10-16 16:34 UTC, merged

2020-10-16 18:24 UTC, ClutchplateDude commented
Hey @mholeys, are you active on our Slack server? I don't recognize your name here, but you might be using a pseudonym :-)

2020-10-16 21:21 UTC, mholeys commented
No I haven't been active on Slack, joined the other day, should be same name. First slack outside of small groups

2020-10-17 18:18 UTC, mholeys commented
Just in case someone else comes across this issue, seems like bluetooth doesn't work with WiFi enabled